import { createPlmWorkItem, type PlmProvider } from "./plmWrite.js";
import { logger } from "../lib/logger.js";
import type { AegisFinding } from "../../../../shared/types/aegisResult.js";

export interface AegisTicketInput {
  finding: AegisFinding;
  parentExternalId: string; // the original work item's PLM key (e.g. "PAY-214")
  parentTitle: string;
  plmProvider: PlmProvider;
  plmProjectKey: string | null;
  userId: string;
}

/**
 * Create a PLM child work item for an Aegis finding, linked to the original work
 * item. Reuses createPlmWorkItem (Jira issue with parent link / ADO Bug with
 * parent relation) as a "bug" — there is no dedicated sub-task creator. Never
 * throws: logs and returns null on any failure so the scan result is still saved.
 */
export async function createAegisPlmTicket(
  input: AegisTicketInput,
): Promise<{ ticketUrl: string; ticketKey: string } | null> {
  const severityLabel = input.finding.severity.toUpperCase();
  const title = `[SECURITY] ${severityLabel}: ${input.finding.title}`.slice(0, 200);

  const description = [
    `Finding: ${input.finding.detail}`,
    `OWASP: ${input.finding.owasp}`,
    input.finding.lineRef ? `Location: ${input.finding.lineRef}` : "",
    input.finding.cveRef ? `CVE: ${input.finding.cveRef}` : "",
    "",
    `Remediation: ${input.finding.remediation}`,
    "",
    "Generated by Aegis (Blue Mantis security agent)",
    `Parent item: ${input.parentTitle}`,
  ]
    .filter(Boolean)
    .join("\n");

  try {
    const result = await createPlmWorkItem(
      input.userId,
      { plmProvider: input.plmProvider, plmProjectKey: input.plmProjectKey },
      {
        itemType: "bug",
        title,
        description,
        parentExternalId: input.parentExternalId || null,
      },
    );
    return { ticketUrl: result.plmUrl, ticketKey: result.externalId };
  } catch (err) {
    logger.warn({ err, findingId: input.finding.id }, "Aegis PLM ticket creation failed");
    return null;
  }
}
