import Anthropic from "@anthropic-ai/sdk";
import type {
  NarratiaResult,
  RunbookTarget,
  RunbookSection,
} from "../../../../shared/types/narratiaResult.js";

/** One file in the committed change set the runbook documents. */
export interface NarratiaFile {
  filePath: string;
  op: "create" | "edit" | "delete";
  code: string;
}

export interface NarratiaInput {
  itemKey: string; // e.g. "PAY-214"
  itemTitle: string;
  itemType: string;
  itemDescription?: string;
  acceptanceCriteria: string[];

  /** The whole committed change set — the runbook documents every file. */
  files: NarratiaFile[];
  stackDesc?: string;
  branchName: string; // e.g. "task/214"
  prUrl?: string;
  commitHash?: string;

  synthesiaVerdict?: string;
  veriaFindings?: string[];
  aegisFindings?: string[];
  aegisGate?: string;
  testCases?: Array<{ title: string; given: string; when: string; then: string; assertion: string }>;

  target: RunbookTarget;
}

const MAX_CHARS_PER_FILE = 3500;

function renderFiles(files: NarratiaFile[]): string {
  if (files.length === 0) return "(no files)";
  return files
    .map((f) => {
      if (f.op === "delete") return `--- delete ${f.filePath} ---\n(file deleted)`;
      return `--- ${f.op} ${f.filePath} ---\n${f.code.slice(0, MAX_CHARS_PER_FILE)}`;
    })
    .join("\n\n");
}

const NARRATIA_PROMPT = (input: NarratiaInput): string => `
You are Narratia, a technical documentation specialist.
Your role is to generate clear, accurate operational runbooks
for code changes that have been reviewed, tested, and committed.

Work item: ${input.itemKey} — ${input.itemTitle}
Type: ${input.itemType}
Stack: ${input.stackDesc ?? "unknown"}
Branch: ${input.branchName}
${input.prUrl ? `PR: ${input.prUrl}` : ""}

Acceptance criteria:
${input.acceptanceCriteria.length > 0 ? input.acceptanceCriteria.map((c, i) => `${i + 1}. ${c}`).join("\n") : "None provided"}

Description:
${input.itemDescription ?? "None provided"}

Committed change set (${input.files.length} file(s)):
${renderFiles(input.files)}

${input.synthesiaVerdict ? `AI recommendation: ${input.synthesiaVerdict}` : ""}
${input.aegisGate ? `Security gate: ${input.aegisGate}` : ""}
${input.aegisFindings?.length ? `Security findings:\n${input.aegisFindings.map((f) => `- ${f}`).join("\n")}` : ""}
${input.veriaFindings?.length ? `Code review notes:\n${input.veriaFindings.map((f) => `- ${f}`).join("\n")}` : ""}

Generate a complete operational runbook in Markdown.
Be specific — reference actual function names, file paths, and
environment variables from the code above.

The runbook must contain exactly these sections in this order:

## Summary
2-3 sentences. What changed, why, and what it enables.

## What changed
Bullet list of specific changes made, covering EVERY file in the change set —
name each file and what changed in it, and how the files relate (e.g. the
endpoint added to the controller calls the new service method declared on the
interface). Reference actual code.

## Deployment steps
Numbered list of steps to deploy this change. Include environment
variables, config changes, migration steps, service restarts, or
feature flags needed. If none: "Standard deployment — no additional steps."

## Rollback procedure
Numbered steps to roll back. Reference the branch name (${input.branchName})
and PR. Include any data migration rollback if applicable.

## Validation
How to verify this change is working in production — specific endpoints,
expected responses, log lines, or dashboards. Derive from the acceptance
criteria and test cases if available.

## Test cases
${input.testCases?.length ? "List the generated test cases as a table." : "No test cases were generated for this change."}

## Security notes
${input.aegisGate ? `Gate status: ${input.aegisGate}. ${input.aegisFindings?.length ? "Findings:\n" + input.aegisFindings.map((f) => `- ${f}`).join("\n") : "No security findings."}` : "Security scan not run for this change."}

## References
- Work item: ${input.itemKey}
- Branch: ${input.branchName}
${input.prUrl ? `- Pull request: ${input.prUrl}` : ""}
${input.commitHash ? `- Commit: ${input.commitHash}` : ""}
- Generated by: Narratia (Blue Mantis)

Rules:
- Every section must be present, even if it just says "Not applicable."
- Use active voice.
- No generic advice — every line must be specific to this change.
- Format as clean Markdown (rendered in Confluence/Notion).
- Code snippets: fenced code blocks with a language identifier.
- Return the complete Markdown document only — no JSON wrapper.
`;

function parseMarkdownSections(markdown: string): RunbookSection[] {
  const lines = markdown.split("\n");
  const sections: RunbookSection[] = [];
  let current: { title: string; lines: string[] } | null = null;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      if (current) sections.push({ title: current.title, content: current.lines.join("\n").trim() });
      current = { title: line.replace("## ", "").trim(), lines: [] };
    } else if (current) {
      current.lines.push(line);
    }
  }
  if (current) sections.push({ title: current.title, content: current.lines.join("\n").trim() });
  return sections;
}

/**
 * Generate an operational runbook from a committed run. Uses the user's
 * Anthropic key (per-user creds, like Veria/Aegis). Throws on an empty response
 * so the route can mark the runbook failed.
 */
export async function runNarratia(
  input: NarratiaInput,
  creds: { anthropicApiKey?: string },
): Promise<NarratiaResult> {
  const client = new Anthropic({ apiKey: creds.anthropicApiKey });

  const response = await client.messages.create({
    model: "claude-sonnet-4-5",
    max_tokens: 3000,
    messages: [{ role: "user", content: NARRATIA_PROMPT(input) }],
  });

  const markdown = response.content
    .filter((b) => b.type === "text")
    .map((b) => (b as { type: "text"; text: string }).text)
    .join("")
    .trim();

  if (!markdown || markdown.length < 100) {
    throw new Error("Narratia returned an empty or too-short runbook.");
  }

  return {
    title: `Runbook: ${input.itemKey} — ${input.itemTitle}`,
    target: input.target,
    markdown,
    sections: parseMarkdownSections(markdown),
    generatedAt: new Date().toISOString(),
  };
}
